import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";

import ToastProvider from "./providers/ToastProvider";
import LoginModal from "./components/modals/LoginModal";
import CreateModal from "./components/modals/CreateModal";

import getCurrentUser from "./actions/getCurrentUser";
import Navbar from "./components/navbar/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const font = Nunito({
  subsets: ["latin"],
});

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const currentUser = await getCurrentUser();

  return (
    <html lang="en">
      <body className={font.className}>
        <div className=" absolute">
          <ToastProvider />
          <Navbar currentUser={currentUser} />

          <LoginModal />
          <CreateModal />
        </div>

        <div className="pb-28 pt-28">{children}</div>
      </body>
    </html>
  );
}
